version: '3.8'

services:
  php:
    image: php:8.1-fpm
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./portal:/var/www/html
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: tyrell_job
      MYSQL_USER: tyrell_user
      MYSQL_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqldumps:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./portal:/var/www/html
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php
